#!/usr/bin/perl

die "
   This is a simple test driver for Ptml.pm.  It displays a 
   Ptml document with no additional logic.

   Usage: doPtml [-v] template-file-name [section names(s)]
   Where: -v                 : turn on document debug mode
          template-file-name : your template file
          sections name(s)   : select which `.SECTION name's
                               to display. space delimited list 
" if @ARGV < 1;                             

# we don't know where Ptml is installed, so try both
# use Ptml qw{PtmlPrint set_verify};
# use Text::Template::Ptml qw{PtmlPrint set_verify};

BEGIN{ 
   eval "require Ptml";  
   eval "require Text::Template::Ptml";
   import Text::Template::Ptml qw{PtmlPrint set_verify};
}


if ($ARGV[0] =~ m/^-v/oi)
{  shift;
   set_verify();
}

PtmlPrint( shift , \@ARGV);
